try

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -67,12 +67,28 @@ jobs:
           sudo cp raygui/src/raygui.h /usr/local/include/
 
       - name: Build raylib-python-cffi
+        env:
+          RAYLIB_PLATFORM: ${{ matrix.raylib-platform }}
         run: |
           python -m pip install --upgrade pip
           pip3 install "cffi>=1.17.1"
           pip3 install wheel
           pip3 install setuptools
-          RAYLIB_PLATFORM=${{ matrix.raylib-platform }} python setup.py bdist_wheel --plat-name macosx_10_15_x86_64
+          python setup.py bdist_wheel --plat-name macosx_10_15_x86_64
+
+      - name: Test
+        run: |
+          pip3 install dist/*.whl
+          cd /
+          python3 -c 'import pyray; pyray.init_window(100,100,"test")' >/tmp/output 2>&1 || true
+          cat /tmp/output
+          if grep -q "INFO: Initializing raylib" /tmp/output; then
+            echo "Passed"
+            exit 0
+          else
+            echo "Failed"
+            exit 1
+          fi
 
       - name: Upload build Artifact wheel
         uses: actions/upload-artifact@v3.2.1
@@ -226,15 +242,13 @@ jobs:
         run: |
           pip3 install dist/*.whl
           cd /
-          echo "moo"
           python3 -c 'import pyray; pyray.init_window(100,100,"test")' >/tmp/output 2>&1 || true
-          echo "woo"
           cat /tmp/output
           if grep -q "INFO: Initializing raylib" /tmp/output; then
-            echo "boo"
+            echo "Passed"
             exit 0
           else
-            echo "foo"
+            echo "Failed"
             exit 1
           fi
                     
