Sdl backend (#140)
* latest raylib version

* add libwayland-dev

* update headers

* add libxkbcommon-dev

* sdl

* sdl dl

* sdl dl

* sdl2 link flags

* remove glfw header

* try static sdl build

* try to set fpic

* install alsa etc before building sdl

* windows

* fix

* try

* try

* try

* try

* try

* try

* try

* try

* try

* try

* try

* try

* try

* try mac

* try mac

* try mac

* try mac

* try

* try

* try

* try

* try

* try

* try

* try

* try

* try

* try

* try

* try

* try

* try

* try

* try

* try

* try

* try

* try

* try

* try

* try

* try

* try

* try

* try

* try

* try

* try

* try

* try

* try

* try

* try

* try

* update raylib

* try

* try

* try

* try

* try

* try

* try

* try

* try

* try

* try

* try

* try

* try

* try

* update to 5.5

* dont link x11 if using DRM

* update to fixed raylib version

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -4,28 +4,39 @@ name: Build
 on:
   # Triggers the workflow on push or pull request events but only for the master branch
   push:
-    branches: [ master ]
   pull_request:
-    branches: [ master ]
 
   # Allows you to run this workflow manually from the Actions tab
   workflow_dispatch:
 
 
 jobs:
-  build-mac:
+  build-mac-intel:
     runs-on: macos-12
     strategy:
       matrix:
-        python-version: [ '3.8', '3.9', '3.10', '3.11', '3.12', '3.13.0-beta - 3.13.0', 'pypy-3.8', 'pypy-3.9', 'pypy-3.10' ]
+        python-version: [ '3.9', '3.10', '3.11', '3.12', '3.13', 'pypy-3.9', 'pypy-3.10' ]
+        raylib-platform: ['Desktop', 'SDL']
+    env:
+      MACOSX_DEPLOYMENT_TARGET: '10.13'
     steps:
       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
-      - uses: actions/checkout@v2
+      - uses: actions/checkout@v4
         with:
           submodules: recursive
 
+      - name: Build SDL
+        run: |
+          wget https://github.com/libsdl-org/SDL/archive/refs/tags/release-2.30.7.tar.gz
+          tar xvfz release-2.30.7.tar.gz
+          mkdir build
+          cd build
+          cmake ../SDL-release-2.30.7 -DSDL_SHARED=OFF -DSDL_STATIC=ON -DCMAKE_POSITION_INDEPENDENT_CODE=ON -DCMAKE_BUILD_TYPE=Release
+          cmake --build . --config Release
+          sudo cmake --install .
+
       - name: Setup Python
-        uses: actions/setup-python@v2.2.2
+        uses: actions/setup-python@v5
         with:
           # Version range or exact version of a Python version to use, using SemVer's version range syntax.
           python-version: ${{ matrix.python-version }}
@@ -33,7 +44,7 @@ jobs:
           architecture: x64
 
       # Runs a set of commands using the runners shell
-      - name: Build raylib
+      - name: Build raylib without SDL because SDL version has incorrect pkg-config
         run: |
           cd raylib-c
           mkdir build
@@ -42,6 +53,15 @@ jobs:
           make -j2
           sudo make install
 
+      - name: Build raylib with SDL if selected
+        run: |
+          cd raylib-c
+          mkdir build2
+          cd build2
+          cmake -DPLATFORM=${{ matrix.raylib-platform }}  -DBUILD_EXAMPLES=OFF -DCUSTOMIZE_BUILD=ON -DSUPPORT_FILEFORMAT_JPG=ON -DSUPPORT_FILEFORMAT_FLAC=ON -DWITH_PIC=ON -DCMAKE_BUILD_TYPE=Release ..
+          make -j2
+          sudo cp raylib/libraylib.a /usr/local/lib/libraylib.a
+
       - name: Copy extras
         run: |
           sudo cp -r raylib-c/src/external/glfw/include/GLFW /usr/local/include/
@@ -49,12 +69,28 @@ jobs:
           sudo cp raygui/src/raygui.h /usr/local/include/
 
       - name: Build raylib-python-cffi
+        env:
+          RAYLIB_PLATFORM: ${{ matrix.raylib-platform }}
         run: |
           python -m pip install --upgrade pip
           pip3 install "cffi>=1.17.1"
           pip3 install wheel
           pip3 install setuptools
-          python setup.py bdist_wheel --plat-name macosx_10_15_x86_64
+          python setup.py bdist_wheel --plat-name macosx_10_13_x86_64
+
+      - name: Test
+        run: |
+          pip3 install dist/*.whl
+          cd /
+          python3 -c 'import pyray; pyray.init_window(100,100,"test")' >/tmp/output 2>&1 || true
+          cat /tmp/output
+          if grep -q "INFO: Initializing raylib" /tmp/output; then
+            echo "Passed"
+            exit 0
+          else
+            echo "Failed"
+            exit 1
+          fi
 
       - name: Upload build Artifact wheel
         uses: actions/upload-artifact@v3.2.1
@@ -62,37 +98,76 @@ jobs:
           name: wheel
           path: dist/*
 
-
-#  build-mac12-arm64:
-#    runs-on: macos-12
+#  build-mac-universal:
+#    runs-on: macos-14
 #    strategy:
 #      matrix:
-#        python-version: ['3.10', '3.11.0-alpha - 3.11.0' ]
-#        # Requires universal2 build of python, which we get if we ask for 3.10.5 x86! Pypy not available in universal2
+#        python-version: [ '3.8', '3.9', '3.10', '3.11', '3.12', '3.13', 'pypy-3.8', 'pypy-3.9', 'pypy-3.10' ]
+#        raylib-platform: ['Desktop', 'SDL']
+#    env:
+#      MACOSX_DEPLOYMENT_TARGET: 11.0
 #    steps:
-#      - uses: actions/checkout@v2
+#      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
+#      - uses: actions/checkout@v4
 #        with:
 #          submodules: recursive
 #
-#      - name: Setup Python
-#        uses: actions/setup-python@v2.2.2
-#        with:
-#          python-version: ${{ matrix.python-version }}
-#          architecture: x64
+#      - name: Build SDL
+#        run: |
+#          wget https://github.com/libsdl-org/SDL/archive/refs/tags/release-2.30.7.tar.gz
+#          tar xvfz release-2.30.7.tar.gz
+#          mkdir build
+#          cd build
+#          cmake ../SDL-release-2.30.7 -DCMAKE_OSX_ARCHITECTURES="arm64;x86_64" -DSDL_SHARED=OFF -DSDL_STATIC=ON -DCMAKE_POSITION_INDEPENDENT_CODE=ON -DCMAKE_BUILD_TYPE=Release
+#          cmake --build . --config Release
+#          sudo cmake --install .
 #
-#      # Only build raylib for arm64 (although we could make a fat universal2 binary by asking for x86_64 as well)
-#      - name: Build raylib
+#      - name: Setup Python
+#        uses: actions/setup-python@v5
+#        with:
+#          # Version range or exact version of a Python version to use, using SemVer's version range syntax.
+#          python-version: ${{ matrix.python-version }}
+#          architecture: arm64
+#
+#      # Runs a set of commands using the runners shell
+#      - name: Build raylib without SDL because SDL version has incorrect pkg-config
 #        run: |
 #          cd raylib-c
 #          mkdir build
 #          cd build
-#          cmake -DBUILD_EXAMPLES=off -DCMAKE_OSX_ARCHITECTURES="arm64;x86_64"  -DINCLUDE_EVERYTHING=on -DSUPPORT_FILEFORMAT_JPG=on -DWITH_PIC=on -DCMAKE_BUILD_TYPE=Release ..
+#          cmake -DCMAKE_OSX_ARCHITECTURES="arm64;x86_64" -DBUILD_EXAMPLES=OFF -DCUSTOMIZE_BUILD=ON -DSUPPORT_FILEFORMAT_JPG=ON -DSUPPORT_FILEFORMAT_FLAC=ON -DWITH_PIC=ON -DCMAKE_BUILD_TYPE=Release ..
 #          make -j2
 #          sudo make install
+#
+#      - name: Build raylib with SDL if selected
+#        run: |
+#          cd raylib-c
+#          mkdir build2
+#          cd build2
+#          cmake -DPLATFORM=${{ matrix.raylib-platform }} -DCMAKE_OSX_ARCHITECTURES="arm64;x86_64" -DPLATFORM=SDL -DBUILD_EXAMPLES=OFF -DCUSTOMIZE_BUILD=ON -DSUPPORT_FILEFORMAT_JPG=ON -DSUPPORT_FILEFORMAT_FLAC=ON -DWITH_PIC=ON -DCMAKE_BUILD_TYPE=Release ..
+#          make -j2
+#          sudo cp raylib/libraylib.a /usr/local/lib/libraylib.a
+#
 #      - name: Copy extras
 #        run: |
+#          sudo cp -r raylib-c/src/external/glfw/include/GLFW /usr/local/include/
 #          sudo cp physac/src/physac.h /usr/local/include/
 #          sudo cp raygui/src/raygui.h /usr/local/include/
+#
+#      - name: Build raylib-python-cffi
+#        run: |
+#          python -m pip install --upgrade pip
+#          pip3 install "cffi>=1.17.1"
+#          pip3 install wheel
+#          pip3 install setuptools
+#          RAYLIB_PLATFORM=${{ matrix.raylib-platform }} python setup.py bdist_wheel
+#
+#      - name: Upload build Artifact wheel
+#        uses: actions/upload-artifact@v3.2.1
+#        with:
+#          name: wheel
+#          path: dist/*
+
 #
 #      # Name defaults to universal2 and it technically is, but we override name to arm64.  Why don't we make a working universal2 wheel?  Because
 #      # I'd rather have a separate x86_64 that I can test, and I want it to work on 10_15 but I'm not sure a 'macosx_10_15_universal2' is valid
@@ -103,62 +178,7 @@ jobs:
 #          pip3 install cffi
 #          pip3 install wheel
 #          python setup.py bdist_wheel --plat-name macosx_12_0_arm64
-#
-#
-#      - name: Upload build Artifact wheel
-#        uses: actions/upload-artifact@v3.2.1
-#        with:
-#          name: wheel
-#          path: dist/*
-#
-#
-#  build-mac11-arm64:
-#    runs-on: macos-11
-#    strategy:
-#      matrix:
-#        python-version: [ '3.10.5' ]
-#        # Requires universal2 build of python, which we get if we ask for 3.10.5 x86! Pypy not available in universal2
-#    env:
-#      MACOSX_DEPLOYMENT_TARGET: 11.6
-#    steps:
-#      - uses: actions/checkout@v2
-#        with:
-#          submodules: recursive
-#
-#      - name: Setup Python
-#        uses: actions/setup-python@v2.2.2
-#        with:
-#          python-version: ${{ matrix.python-version }}
-#          architecture: x64
-#
-#      #  build raylib for arm64 and x86_64 as well
-#      - name: Build raylib
-#        run: |
-#          cd raylib-c
-#          mkdir build
-#          cd build
-#          cmake -DBUILD_EXAMPLES=off -DCMAKE_OSX_ARCHITECTURES="arm64;x86_64" -DINCLUDE_EVERYTHING=on -DSUPPORT_FILEFORMAT_JPG=on -DWITH_PIC=on -DCMAKE_BUILD_TYPE=Release ..
-#          make -j2
-#          sudo make install
-#      - name: Copy extras
-#        run: |
-#          sudo cp physac/src/physac.h /usr/local/include/
-#          sudo cp raygui/src/raygui.h /usr/local/include/
-#
-#
-#      - name: Build raylib-python-cffi
-#        run: |
-#          python -m pip install --upgrade pip
-#          pip3 install cffi
-#          pip3 install wheel
-#          python setup.py bdist_wheel --plat-name macosx_11_0_arm64
-#
-#      - name: Upload build Artifact wheel
-#        uses: actions/upload-artifact@v3.2.1
-#        with:
-#          name: wheel
-#          path: dist/*
-#
+
 
 
   build-linux:
@@ -167,30 +187,43 @@ jobs:
       # You can use PyPy versions in python-version.
       # For example, pypy2 and pypy3
       matrix:
-        python-version: [ '3.8', '3.9', '3.10', '3.11', '3.12', '3.13.0-beta - 3.13.0',  'pypy-3.8', 'pypy-3.9', 'pypy-3.10' ]
+        python-version: [ '3.9', '3.10', '3.11', '3.12', '3.13', 'pypy-3.9', 'pypy-3.10' ]
+        raylib-platform: ['Desktop', 'SDL', 'DRM']
     steps:
       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
-      - uses: actions/checkout@v2
+      - uses: actions/checkout@v4
         with:
           submodules: recursive
 
       - name: Setup Python
-        uses: actions/setup-python@v2.2.2
+        uses: actions/setup-python@v5
         with:
           # Version range or exact version of a Python version to use, using SemVer's version range syntax.
           python-version: ${{ matrix.python-version }}
           # The target architecture (x86, x64) of the Python interpreter.
           architecture: x64
 
+      - name: install prereqs
+        run: |
+          sudo apt update
+          sudo apt install libasound2-dev mesa-common-dev libx11-dev libxrandr-dev libxi-dev xorg-dev libgl1-mesa-dev libglu1-mesa-dev libwayland-dev libxkbcommon-dev
+      - name: Build SDL
+        run: |          
+          wget https://github.com/libsdl-org/SDL/archive/refs/tags/release-2.30.7.tar.gz
+          tar xvfz release-2.30.7.tar.gz
+          mkdir build
+          cd build
+          cmake ../SDL-release-2.30.7 -DSDL_SHARED=OFF -DSDL_STATIC=ON -DCMAKE_POSITION_INDEPENDENT_CODE=ON -DCMAKE_BUILD_TYPE=Release
+          cmake --build . --config Release
+          sudo cmake --install .
+
       # Runs a set of commands using the runners shell
       - name: Build raylib
         run: |
-          sudo apt update
-          sudo apt install libasound2-dev mesa-common-dev libx11-dev libxrandr-dev libxi-dev xorg-dev libgl1-mesa-dev libglu1-mesa-dev
           cd raylib-c
           mkdir build
           cd build
-          cmake -DBUILD_EXAMPLES=OFF -DCUSTOMIZE_BUILD=ON -DSUPPORT_FILEFORMAT_JPG=ON -DSUPPORT_FILEFORMAT_FLAC=ON -DWITH_PIC=ON -DCMAKE_BUILD_TYPE=Release -DOpenGL_GL_PREFERENCE=GLVND ..
+          cmake -DPLATFORM=${{ matrix.raylib-platform }} -DBUILD_EXAMPLES=OFF -DCUSTOMIZE_BUILD=ON -DSUPPORT_FILEFORMAT_JPG=ON -DSUPPORT_FILEFORMAT_FLAC=ON -DWITH_PIC=ON -DCMAKE_BUILD_TYPE=Release -DOpenGL_GL_PREFERENCE=GLVND ..
           make -j2
           sudo make install
       - name: Copy extras
@@ -199,12 +232,28 @@ jobs:
           sudo cp physac/src/physac.h /usr/local/include/
           sudo cp raygui/src/raygui.h /usr/local/include/
       - name: Build raylib-python-cffi
+        env:
+          RAYLIB_PLATFORM: ${{ matrix.raylib-platform }}
         run: |
           python -m pip install --upgrade pip
           pip3 install "cffi>=1.17.1"
           pip3 install wheel
           pip3 install setuptools
           python setup.py bdist_wheel --plat-name manylinux2014_x86_64
+      - name: Test
+        run: |
+          pip3 install dist/*.whl
+          cd /
+          python3 -c 'import pyray; pyray.init_window(100,100,"test")' >/tmp/output 2>&1 || true
+          cat /tmp/output
+          if grep -q "INFO: Initializing raylib" /tmp/output; then
+            echo "Passed"
+            exit 0
+          else
+            echo "Failed"
+            exit 1
+          fi
+                    
 
       - name: Upload build Artifact wheel
         uses: actions/upload-artifact@v3.2.1
@@ -213,36 +262,7 @@ jobs:
           path: dist/*
 
 
-#  build-rpi:
-#    runs-on: rpi
-#    steps:
-#      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
-#      - uses: actions/checkout@v2
-#        with:
-#          submodules: recursive
-#
-#      - name: Build raylib
-#        run: |
-#          cd raylib-c
-#          mkdir build
-#          cd build
-#          cmake -DBUILD_EXAMPLES=off -DINCLUDE_EVERYTHING=on -DSUPPORT_FILEFORMAT_JPG=on -DWITH_PIC=on -DCMAKE_BUILD_TYPE=Release -DOpenGL_GL_PREFERENCE=GLVND ..
-#          make -j2
-#          make install
-#      - name: Copy extras
-#        run: |
-#          cp physac/src/physac.h /usr/local/include/
-#          cp raygui/src/raygui.h /usr/local/include/
-#
-#      - name: Build raylib-python-cffi
-#        run: |
-#          python3 setup.py bdist_wheel
-#
-#      - name: Upload build Artifact wheel
-#        uses: actions/upload-artifact@v3.2.1
-#        with:
-#          name: wheel
-#          path: dist/*
+
 
   build-windows:
     # The type of runner that the job will run on
@@ -251,15 +271,27 @@ jobs:
       # You can use PyPy versions in python-version.
       # For example, pypy2 and pypy3
       matrix:
-        python-version:  [ '3.8', '3.9', '3.10', '3.11', '3.12', '3.13.0-beta - 3.13.0',  'pypy-3.8', 'pypy-3.9', 'pypy-3.10' ]
+        python-version:  [ '3.9', '3.10', '3.11', '3.12', '3.13', 'pypy-3.9', 'pypy-3.10' ]
+        raylib-platform: ['Desktop', 'SDL']
     steps:
-      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
-      - uses: actions/checkout@v2
+      - uses: actions/checkout@v4
         with:
           submodules: recursive
 
+      - name: Download SDL2
+        run: curl -L -o SDL2.zip https://github.com/libsdl-org/SDL/releases/download/release-2.30.8/SDL2-devel-2.30.8-VC.zip
+
+      - name: Create extraction directory
+        run: mkdir ${{ runner.temp }}\SDL2
+
+      - name: Unzip SDL2
+        run: tar -xf SDL2.zip -C ${{ runner.temp }}\SDL2 --strip-components=1
+
+      - name: Set SDL2_DIR environment variable
+        run: echo SDL2_DIR=${{ runner.temp }}\SDL2\cmake >> $env:GITHUB_ENV
+
       - name: Setup Python
-        uses: actions/setup-python@v2.2.2
+        uses: actions/setup-python@v5
         with:
           # Version range or exact version of a Python version to use, using SemVer's version range syntax.
           python-version: ${{ matrix.python-version }}
@@ -274,14 +306,18 @@ jobs:
           cd raylib-c
           mkdir build
           cd build
-          cmake -DBUILD_EXAMPLES=OFF -DCUSTOMIZE_BUILD=ON -DSUPPORT_FILEFORMAT_JPG=ON -DSUPPORT_FILEFORMAT_FLAC=ON -DWITH_PIC=ON -DCMAKE_BUILD_TYPE=Release ..
+          cmake -DPLATFORM=${{ matrix.raylib-platform }}  -DBUILD_EXAMPLES=OFF -DCUSTOMIZE_BUILD=ON -DSUPPORT_FILEFORMAT_JPG=ON -DSUPPORT_FILEFORMAT_FLAC=ON -DWITH_PIC=ON -DCMAKE_BUILD_TYPE=Release ..
           msbuild raylib.sln /target:raylib /property:Configuration=Release
           copy raylib\Release\raylib.lib ..\..
           cd ..\..
         shell: cmd
 
       - name: Build raylib-python-cffi
+        env:
+          RAYLIB_PLATFORM: ${{ matrix.raylib-platform }}
         run: |
+          copy ${{ runner.temp }}\SDL2\lib\x64\SDL2.lib .
+          copy ${{ runner.temp }}\SDL2\lib\x64\SDL2.dll raylib\
           python -m pip install --upgrade pip
           pip3 install "cffi>=1.17.1"
           pip3 install wheel
@@ -292,6 +328,21 @@ jobs:
           del raylib\dynamic\32bit\* >nul 2>&1
           python setup.py bdist_wheel
         shell: cmd
+
+      - name: Test
+        shell: bash
+        run: |
+          pip3 install --no-deps dist/*.whl
+          cd /
+          python3 -c 'import pyray; pyray.init_window(100,100,"test")' >/tmp/output 2>&1 || true
+          cat /tmp/output
+          if grep -q "INFO: Initializing raylib" /tmp/output; then
+            echo "Passed"
+            exit 0
+          else
+            echo "Failed"
+            exit 1
+          fi
           
       - name: Upload build Artifact wheel
         uses: actions/upload-artifact@v3.2.1
@@ -304,12 +355,12 @@ jobs:
 
     steps:
       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
-      - uses: actions/checkout@v2
+      - uses: actions/checkout@v4
         with:
           submodules: recursive
 
       - name: Setup Python
-        uses: actions/setup-python@v2.2.2
+        uses: actions/setup-python@v5
         with:
           # Version range or exact version of a Python version to use, using SemVer's version range syntax.
           python-version: '3.12'
@@ -319,7 +370,7 @@ jobs:
       - name: Build raylib
         run: |
           sudo apt update
-          sudo apt install libasound2-dev mesa-common-dev libx11-dev libxrandr-dev libxi-dev xorg-dev libgl1-mesa-dev libglu1-mesa-dev
+          sudo apt install libasound2-dev mesa-common-dev libx11-dev libxrandr-dev libxi-dev xorg-dev libgl1-mesa-dev libglu1-mesa-dev libwayland-dev libxkbcommon-dev
           cd raylib-c
           mkdir build
           cd build
@@ -351,12 +402,12 @@ jobs:
 
     steps:
       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
-      - uses: actions/checkout@v2
+      - uses: actions/checkout@v4
         with:
           submodules: recursive
 
       - name: Setup Python
-        uses: actions/setup-python@v2.2.2
+        uses: actions/setup-python@v5
         with:
           # Version range or exact version of a Python version to use, using SemVer's version range syntax.
           python-version: '3.12'
